apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - services.yaml
  - ingress.yaml
  - rollout.yaml
  - analysis-error-rate.yaml
  - hpa.yaml
  - pdb.yaml
# its ConfigMap is generated one level up (../kustomization.yaml) from config.env
